### ISSUE TITLE
dns_options_listen_on doesnt allow IP address as input

### ISSUE THREAD

**Issue by Troels51** [robertdebock/ansible-role-dns#12]
## Describe the bug

It looks like the dns_options_listen_on variable doesn't work as described.
I expected I could add an IP address to this list, and it would only listen on that interface. 
But an IP address can't be used as any other string than "any" or "none" are filtered.
Did I read the documentation wrong, or is this a bug?

## Playbook
I won't share the entire the file, but the important option is this.

```yaml
....
dns_options_listen_on:
  - "10.222.222.1"
....
```

## Output

```
failed: [demo_room -> localhost] (item=10.222.222.1) => {"ansible_loop_var": "item", "assertion": "item in [ \"any\", \"none\" ]", "changed": false, "evaluated_to": false, "item": "10.222.222.1", "msg": "Assertion failed"}
```

## Environment

- Control node OS: Ubuntu 22.04.1 LTS
- Control node Ansible version:  2.13.4
- Managed node OS: Ubuntu 22.04.1 LTS

**Comment by robertdebock** [comment]
I [think](https://www.zytrax.com/books/dns/ch7/hkpng.html#listen-on) you are correct. Give me a moment to review and change the role.

**Comment by robertdebock** [comment]
[This commit](https://github.com/robertdebock/ansible-role-dns/commit/62366ba270b57bfe53336979f3b7dfb55355cefe) should improve your situation.

**Comment by Troels51** [comment]
Nice. Thanks!
