### ISSUE TITLE
Molecule: missing scenario "ec2"

### ISSUE THREAD

**Issue by esolitos** [robertdebock/ansible-role-dns#4]
The README indicates that it's possible to run the tests using AWS, indicating that one should use `molecule test --scenario-name ec2`, however such scenario doesn't seem to be available, only the "default" scenario (using docker) is provided.

**Comment by esolitos** [comment]
Looking into the recent code changes it seems that `molecule` was superseded by `tox`, so it seems to be only a matter of updating the docs, isn't it?

**Comment by robertdebock** [comment]
Correct, thanks. I'm in the middle of transitioning.

I'll keep this issue open until I can verify that the documentation does not mention ec2 anymore.

Thanks for your feedback!

**Comment by robertdebock** [comment]
I just released a new version that does not have the EC2 references anymore.

Once again, thanks for the input.
